name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-24.04
    env:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://airflow_user:airflow_pass@localhost/airflow_db
      AIRFLOW__CORE__EXECUTOR: airflowHPC.executors.resource_executor.ResourceExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /home/runner/work/airflowHPC/airflowHPC/airflowHPC/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: False
      RADICAL_UTILS_NO_ATFORK: 1
    steps:

    # The gitlab runner comes with mysql installed by default
    - name: Setup MySQL
      run: |
        sudo systemctl start mysql
        sudo mysql --user=root --password=root -e "CREATE DATABASE airflow_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
        sudo mysql --user=root --password=root -e "CREATE USER 'airflow_user' IDENTIFIED BY 'airflow_pass';"
        sudo mysql --user=root --password=root -e "GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow_user'"
        sudo mysql --user=root --password=root -e "FLUSH PRIVILEGES;"

    - uses: mpi4py/setup-mpi@v1
      with:
        mpi: openmpi

    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          '**/requirements.txt'
          '**/pyproject.toml'
    - run: |
        pip install -e .[mysql]
        pip install -r requirements.txt

    - name: Run tests
      run: |
        airflow db init
        pytest tests/replex.py

    - name: Install GROMACS
      run: |
          sudo apt-get update
          sudo apt-get install -y gromacs

    - name: Run gmx_multi DAG
      run: |
        airflow db init
        airflow dags backfill -s 2024-07-23 --reset-dagruns -y run_gmx
