name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: openmpi

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: Setup CMake
      uses: threeal/cmake-action@main
      with:
        generator: Ninja

    - name: Install GROMACS
      run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://ftp.gromacs.org/gromacs/gromacs-2023.3.tar.gz
          tar xfz gromacs-2023.3.tar.gz
          cd gromacs-2023.3
          cmake -S . -B build -DGMX_BUILD_OWN_FFTW=ON -DGMX_MPI=ON -DBUILD_TESTING=OFF
          make -j $(nproc)
          sudo make -j $(nproc) install
          export gmxapi_ROOT=/usr/local/gromacs/

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/replex.py
