name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: openmpi

    - name: Install GROMACS
      run: |
          sudo apt-get update
          sudo apt-get install -y wget gromacs
          export gmxapi_ROOT=/usr/local/gromacs/

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/replex.py
