name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup MySQL
      uses: marketplacer/setup-mysql@v1.1
      with:
        version: '5.7'
        root_password: 'airflow_password'
        databases: |
          airflow_db
        users: |
          airflow_user:airflow_pass
        env: |
          AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqldb://airflow_user:airflow_pass@localhost/airflow_db

    - name: Run tests
      run: |
        pytest tests/replex.py
