name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: openmpi

    - uses: lukka/get-cmake@latest

    - name: Install GROMACS
      run: |
          sudo apt-get update
          sudo apt-get install -y wget fftw3
          wget https://ftp.gromacs.org/gromacs/gromacs-2023.3.tar.gz
          tar xfz gromacs-2023.3.tar.gz
          cd gromacs-2023.3
          mkdir build
          cd build
          cmake .. -DGMX_BUILD_OWN_FFTW=OFF -DGMX_MPI=ON -DBUILD_TESTING=OFF -DGMX_SIMD=AVX2_256 -DGMX_INSTALL_NBLIB_API=OFF
          make -j $(nproc)
          sudo make -j $(nproc) install

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        export gmxapi_ROOT=/usr/local/gromacs/
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/replex.py
